<?php

require_once "Mage/Catalog/controllers/CategoryController.php";
class Boxalino_Intelligence_CategoryController extends Mage_Catalog_CategoryController{

    public function viewAction()
    {
        $bxHelperData = Mage::helper('intelligence');
        try{
            if($bxHelperData->isNavigationEnabled()){
                if(count($bxHelperData->getAdapter()->getEntitiesIds()) == 0){
                    $bxHelperData->setFallback(true);
                }
            }
        }catch(\Exception $e){
            Mage::logException($e);
            $bxHelperData->setFallback(true);
        }

        parent::viewAction(); // TODO: Change the autogenerated stub
    }
}