<?php
/**
 * @see Boxalino_Intelligence_Block_Journey_Profiler
 */
?>
<div class="bx-journey-profiler">
    <div class="bx-journey-profiler-wrapper">
        <div class="bx-journey-profiler">
            <form class="bx-journey-profiler-form" id="bx-journey-profiler-form">
                <input type="hidden" name="form_key" id="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
                <div id="bx-profiler-question"></div>
                <div class="bx-profiler-button-continue-wrapper"></div>
            </form>
        </div>
        <div id="bx-profiler-progress-wrapper" style="display:none;"></div>
        <div id="bx-profiler-error" style="display:none;"></div>
    </div>
</div>
<script type="text/javascript">
    var bxProfiler = new BxProfiler(
        '<?php echo $this->getLoadUrl()?>',
        '<?php echo $this->getSubmitUrl()?>',
        '<?php echo $this->getSendProfilerRequestUrl()?>',
        '<?php echo $this->getSubmitEventCustomer()?>',
        '<?php echo $this->getSubmitEventVisitor()?>',
        '<?php echo $this->displayProgress()?>',
        '<?php echo $this->getData("choice")?>',
        <?php echo $this->getQuestions()?>
    );
</script>
