<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <?php $selected = $_item->getSelected(); ?>
        <li class="item <?php echo $_item->getType(); echo $selected == true ?  ' selected' : ''; ?>">
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo $this->escapeHtml($selected == true ? $_item->getRemoveUrl() : $_item->getUrl()) ?>">
                    <?php echo $_item->getLabel() ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif; ?>
                </a>
            <?php else: ?>
                <span>
                <?php echo $_item->getLabel(); ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif; ?>
            </span>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
