<?php

  if($this->isPluginActive()) {

    $response = $this->getResponse();

    if (!empty($response)) {


    if($response->getSearchMessageTitle() != "" && $response->getSearchMessageMainImage() == "") { ?>

      <div class="bx-search-message">
          <a href="<?php echo $response->getSearchMessageLink(); ?>" style="text-decoration:none;">
              <div class="bx-search-message-title">
                  <h3 class="bx-search-message-title"  style="<?php echo $response->getSearchMessageTitleStyle(); ?>"><?php echo $response->getSearchMessageTitle(); ?></h3>
                  <div class="bx-search-message-description" style="<?php echo $response->getSearchMessageDescriptionStyle(); ?>"><?php echo $response->getSearchMessageDescription(); ?></div>
              </div>
              <div class="bx-search-message-side-image" align="right"><img src="<?php echo $response->getSearchMessageSideImage(); ?>" alt="" /></div>
          </a>
      </div>

    <?php

    }

    if($response->getSearchMessageMainImage() != "") {

    ?>

    <div class="bx-search-message">
        <a href="<?php echo $response->getSearchMessageLink(); ?>">
            <span class="content" style="float: left;">
                <strong class="bx-search-message-title"  style="<?php echo $response->getSearchMessageTitleStyle(); ?> margin-bottom: 0px;"><?php echo $response->getSearchMessageTitle(); ?></strong>
            </span>
            <span class="bx-search-message-main-image" style="float: left;">
                <img src="<?php echo $response->getSearchMessageMainImage(); ?>" alt="" style ="width: 100%;"/>
            </span>
        </a>
    </div>

    <?php
    }

    }

  }

?>
