<?php

if ($this->isActive()) {
    $this->prepareRecommendations();
    $hitCount = $this->getHitCount();
    $jssorSlides = $this->getBannerSlides();
    $jssorSlideTransitions = $this->getBannerJssorSlideTransitions();
    $jssorSlideBreaks = $this->getBannerJssorSlideBreaks();
    $jssorSlideControls = $this->getBannerJssorSlideControls();
    $jssorOptions = $this->getBannerJssorOptions();
    $jssorMaxWidth = $this->getBannerJssorMaxWidth();
    $jssorCSS = $this->getBannerJssorCSS();
    $jssorStyle = $this->getBannerJssorStyle();
    $jssorLoadingScreen = $this->getBannerJssorLoadingScreen();
    $jssorSlidesStyle = $this->getBannerJssorSlidesStyle();
    $jssorBulletNavigator = $this->getBannerJssorBulletNavigator();
    $jssorArrowNavigator = $this->getBannerJssorArrowNavigator();
    $jssorFunction = $this->getBannerFunction();
    $jssorLayout = $this->getBannerLayout();
    $configVals = $this->getValues();
    $jssorConfigId = $this->getBannerJssorId();
    $jssorId = $configVals['jssorID'];
    $jssorIndex = $configVals['jssorIndex'];

    // replace id from Intelligence with id from block configuration
    $jssorOptions = str_replace($jssorConfigId, $jssorId, $jssorOptions);
    $jssorFunction = str_replace($jssorConfigId, $jssorId, $jssorFunction);

    // if there is only one banner or it is using the 'small' layout, don't be draggable
    if ($hitCount < 2 || $jssorLayout == 'small') {
        $jssorOptions = substr_replace($jssorOptions, '$DragOrientation:0, ', 1, 0);
    }

    if ($this->check()) {
        ?>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
        <script type="text/javascript">
            <?php echo $jssorId ?>_slider_init = function() {
                var <?php echo $jssorId ?>_SlideoTransitions = <?php echo $jssorSlideTransitions ?>;
                var <?php echo $jssorId ?>_SlideoBreaks = <?php echo $jssorSlideBreaks ?>;
                var <?php echo $jssorId ?>_SlideoControls = <?php echo $jssorSlideControls ?>;
                var <?php echo $jssorId ?>_options = <?php echo $jssorOptions ?>;
                var <?php echo $jssorId ?>_slider = new $JssorSlider$(<?php echo $jssorId ?>, <?php echo $jssorId ?>_options);
                var MAX_WIDTH = <?php echo $jssorMaxWidth ?>;

                function ScaleSlider() { <?php echo $jssorFunction ?> }
                ScaleSlider();
                $Jssor$.$AddEvent(window, "load", ScaleSlider);
                $Jssor$.$AddEvent(window, "resize", ScaleSlider);
                $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            };
        </script>

        <style>
            <?php echo $jssorCSS ?>
        </style>

        <div id="<?php echo $jssorId ?>" style="<?php echo $jssorStyle ?>">
            <?php echo $jssorLoadingScreen ?>
            <div data-u="slides" style="<?php echo $jssorSlidesStyle ?>">
                <?php
                foreach($jssorSlides as $bannerSlideId => $values ) {
                    echo $values['div'];
                }
                ?>
            </div>

            <?php if ($hitCount > 1 && $jssorLayout != 'small'){
                echo $jssorBulletNavigator;
                echo $jssorArrowNavigator;
            }; ?>

        </div>
        <script type="text/javascript"><?php echo $jssorId ?>_slider_init();</script>
        <?php
    }
}
?>
