<?php $blogArticle = $this->getData('blogArticle'); ?>

<li class="item product product-item blogArticlePost">

  <figure>
    <a href="<?php echo $blogArticle[$this->getLinkFieldName()] ?>">
      <img class="blogArticleImage"
        width="<?php echo $this->getBlogArticleImageWidth() ?>"
        height="<?php echo $this->getBlogArticleImageHeight() ?>"
        src="<?php echo $blogArticle[$this->getMediaUrlFieldName()] ?>"
       >
    </a>
  </figure>

  <div class="blogArticleTextArea">

  <h4 class="blogArticleHeader">
    <a href="<?php echo $blogArticle[$this->getLinkFieldName()] ?>">
      <?php echo $this->escapeHtml($blogArticle['title']) ?>
    </a>
  </h4>

  <div class="blogArticleExcerpt">
    <?php echo $this->escapeHtml($blogArticle[$this->getExcerptFieldName()]); ?>
  </div>

  </div>
</li>
