<?php if ($this->isActive()) { ?>

  <div class="block blog">
    <div class="block-title title">
      <strong><?php echo $this->getBlogArticleTitle() ?></strong></div>
    <div class="block-content content">
      <div class="products wrapper grid products-grid products-blog">
        <ol class="blogArticleOrderedList">
          <?php foreach ($this->getBlogArticles() as $blogArticle) { ?>
            <?php echo $this->getLayout()->createBlock('Boxalino_Intelligence_Block_Product_List_Blog')->setData('blogArticle', $blogArticle)->setTemplate("boxalino/blog_article.phtml")->toHtml(); ?>
          <?php } ?>
        </ol>
      </div>
    </div>
  </div>

<?php } ?>
