<?php if($this->isPluginEnabled()) :?>
    <?php $widget = $this->getData('widget'); ?>
    <h1><?php /* @escapeNotVerified */ echo __('Recommendation for %s', $this->getData('title'))?></h1>
    <?php $_productCollection = $this->_getLoadedProductCollection(); ?>
    <?php if($_productCollection->count()): ?>
        <div class="box-collateral box-up-sell">
            <table class="products-grid" id="upsell-product-table">
                <tr>
                    <?php foreach($_productCollection as $product): ?>
                        <td>
                            <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->escapeHtml($product->getName()) ?>" /></a>
                            <h3 class="product-name"><a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h3>
                            <?php echo $this->getPriceHtml($product, true, '-upsell') ?>
                            <?php echo $this->getReviewsSummaryHtml($product) ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            </table>
            <script type="text/javascript">decorateTable('upsell-product-table')</script>
        </div>
    <?php endif ?>
<?php endif ?>
