<?php
/**
 * Boxalino Script Block
 */

/** @var $this Boxalino_CemSearch_Block_Script */

/** @var $_helper Boxalino_Intelligence_Helper_Data */
$_helper = Mage::helper('boxalino_intelligence');

// get account
$account = Mage::getStoreConfig('bxGeneral/general/account_name');
?>
<script>
    var _bxq = _bxq || []
    _bxq.push(['setAccount', <?php echo json_encode($account); ?>]);
    <?php echo $this->getScripts(); ?>

    <?php if ($_helper->isTrackerEnabled()): ?>
    _bxq.push(['trackPageView']);
    <?php endif; ?>

    <?php // FIXME This method does not exist. Direct $_GET access is not forbidden. ?>
    <?php //if ($this->isSearch()): ?>
    <?php //echo $_helper->reportSearch($_GET['q'], $_helper->getFiltersValues($_GET)); ?>
    <?php //endif; ?>

    (function () {
        var s = document.createElement('script');
        s.async = 1;
        s.src = '//cdn.bx-cloud.com/frontend/rc/js/ba.min.js';
        document.getElementsByTagName('head')[0].appendChild(s);
    })();
</script>
